name: CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  NODE_VERSION: 16

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Install Dependencies & Build
        run: |
          npm ci    
          npm run build-dist-docs
